bsp: imx: add bsp for imx8mpevk
foundriesio/lmp-kernel-cache pull request #13
Opened 2021-08-06 22:33 UTC by Tim-Anderson

Signed-off-by: Tim Anderson <tim.anderson@foundries.io>

2021-08-07 01:44 UTC, mike-scott requested changes

2021-08-07 01:44 UTC, mike-scott commented on bsp/imx/imx8mp-lpddr4-evk-standard.scc
> +define KMACHINE imx8mpevk
This needs an update to match new naming.

2021-08-07 01:44 UTC, mike-scott commented on bsp/imx/imx8mp-lpddr4-evk.scc
> +kconf hardware imx8mpevk.cfg
This needs an update to match the new filename

2021-08-09 11:54 UTC, angolini approved these changes
nothing else to comment, LGTM

2021-08-09 12:48 UTC, vanmaegima approved these changes
LGTM

2021-08-09 21:32 UTC, ricardosalveti commented
Can you update the commit subject line to use the new board name instead?

2021-08-09 21:32 UTC, ricardosalveti approved these changes
LGTM other than my subject machine renaming comment.

2021-08-09 21:35 UTC, Tim-Anderson commented
done

On Mon, Aug 9, 2021 at 2:32 PM Ricardo Salveti ***@***.***>
wrote:

> Can you update the commit subject line to use the new board name instead?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/foundriesio/lmp-kernel-cache/pull/13#issuecomment-895564940>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAROSL7D5M6TSBJQPQSBQD3T4BCOVANCNFSM5BWWUDIQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-09 21:36 UTC, merged